### ISSUE TITLE
error messege issue

### ISSUE THREAD

**Issue by alznn** [System-T/DimSim#1]
https://github.com/System-T/DimSim/blob/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b/code/dimsim/dimsim/dimsim.py#L330

Should this  be "return"?

**Comment by qk63030898** [comment]
> [DimSim/code/dimsim/dimsim/dimsim.py](https://github.com/System-T/DimSim/blob/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b/code/dimsim/dimsim/dimsim.py#L330)
> 
> Line 330 in [d5b8410](/System-T/DimSim/commit/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b)
> 
>  print("{}{}{}".format(self.consonant, self.vowel, self.tone)) 
> Should this be "return"?


Thanks for catching this, it's been fixed.

**Comment by qk63030898** [comment]
> [DimSim/code/dimsim/dimsim/dimsim.py](https://github.com/System-T/DimSim/blob/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b/code/dimsim/dimsim/dimsim.py#L330)
> 
> Line 330 in [d5b8410](/System-T/DimSim/commit/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b)
> 
>  print("{}{}{}".format(self.consonant, self.vowel, self.tone)) 
> Should this be "return"?


Thanks for catching this. It's been fixed.
