### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by alznn** [System-T/DimSim#2]
https://github.com/System-T/DimSim/blob/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b/code/dimsim/dimsim/dimsim.py#L349

您好，想請教在這段 consonant 判斷式設計上的意義，

在實做上，以 wang2 為例，進入判段式後
將 vowel 取代為 u+self.vowel
並使 consonant w 為 ""

回到 getEditDistanceClose_TwoDCode 後，"" mapping 到 99999.0，

接著進入到  cDis = abs(getDistance_TwoDCode(twoDcode_consonant_a, twoDcode_consonant_b)) ，在此段中，因傳入的值為 99999.0 ，因此造成 x2 or y2 沒辦法 mapping 到 value，進而產生 **TypeError: 'float' object is not iterable**

因為不了解將 consonet w 取代成 "" 的意義，因此不敢隨意修改，希望可以請教設計上的相關事宜，謝謝您

**Comment by qk63030898** [comment]
Thanks for your comment, it was a bug, and now it's been fixed. We also updated the corresponding pypi project. Now, if you want to try the new version, you can do 

pip install chinesesoundex-1.0

Thanks

**Comment by qk63030898** [comment]
> [DimSim/code/dimsim/dimsim/dimsim.py](https://github.com/System-T/DimSim/blob/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b/code/dimsim/dimsim/dimsim.py#L349)
> 
> Line 349 in [d5b8410](/System-T/DimSim/commit/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b)
> 
>  if self.consonant is "w": 
> 您好，想請教在這段 consonant 判斷式設計上的意義，
> 
> 在實做上，以 wang2 為例，進入判段式後
> 將 vowel 取代為 u+self.vowel
> 並使 consonant w 為 ""
> 
> 回到 getEditDistanceClose_TwoDCode 後，"" mapping 到 99999.0，
> 
> 接著進入到 cDis = abs(getDistance_TwoDCode(twoDcode_consonant_a, twoDcode_consonant_b)) ，在此段中，因傳入的值為 99999.0 ，因此造成 x2 or y2 沒辦法 mapping 到 value，進而產生 **TypeError: 'float' object is not iterable**
> 
> 因為不了解將 consonet w 取代成 "" 的意義，因此不敢隨意修改，希望可以請教設計上的相關事宜，謝謝您
Thanks for your comment, it was a bug, and now it's been fixed. We also updated the corresponding pypi project. Now, if you want to try the new version, you can do

pip install chinesesoundex-1.0

Thanks

**Comment by qk63030898** [comment]
> [DimSim/code/dimsim/dimsim/dimsim.py](https://github.com/System-T/DimSim/blob/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b/code/dimsim/dimsim/dimsim.py#L349)
> 
> Line 349 in [d5b8410](/System-T/DimSim/commit/d5b8410eb0c84dc9e4d613c810bf7ea21780a98b)
> 
>  if self.consonant is "w": 
> 您好，想請教在這段 consonant 判斷式設計上的意義，
> 
> 在實做上，以 wang2 為例，進入判段式後
> 將 vowel 取代為 u+self.vowel
> 並使 consonant w 為 ""
> 
> 回到 getEditDistanceClose_TwoDCode 後，"" mapping 到 99999.0，
> 
> 接著進入到 cDis = abs(getDistance_TwoDCode(twoDcode_consonant_a, twoDcode_consonant_b)) ，在此段中，因傳入的值為 99999.0 ，因此造成 x2 or y2 沒辦法 mapping 到 value，進而產生 **TypeError: 'float' object is not iterable**
> 
> 因為不了解將 consonet w 取代成 "" 的意義，因此不敢隨意修改，希望可以請教設計上的相關事宜，謝謝您



Thanks for your comment, it was a bug, and now it's been fixed. We also updated the corresponding pypi project. Now, if you want to try the new version, you can do

pip install chinesesoundex-1.0

Thanks

**Comment by yunyaoli** [comment]
Issue has been fixed.
